logging:
  level: INFO
  loggers:
    org.example: DEBUG

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 4000
    type: http

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/dropwizard
  user: root
  password: KevinLara_0
